version: '3.3'

services:
  postgres:
    image: postgres:11.2
    container_name: moe-rank-database
    restart: always
    environment:
      - TZ=UTC
      - PGTZ=UTC
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=moe-rank
    ports:
      - '5432:5432'
    volumes:
      - moe-rank-db-data:/var/lib/postgresql/data
    networks:
      - moe-rank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 5s
      retries: 5

  moe-rank-backend:
    container_name: moe-rank-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: moe-rank-backend:latest
    expose:
      - 8080
    networks:
      - moe-rank-network
    volumes:
      - moe-rank-backend:/var/lib/spring-cloud/config-repo

volumes:
  moe-rank-db-data:
    driver: local
  moe-rank-backend:
    driver: local

networks:
  moe-rank-network:
    driver: bridge